version: '3'

services:
  catalog-module:
    image: nareshtech23/catalog-service
    ports: 
     - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
  redis:
    image: redis:alpine
  Review-Module:
    image: nareshtech23/review-service
    ports:
     - "90:90"
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
  Order-Module:
    image: nareshtech23/order-service
    ports:
     - "95:95"
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
